//GET http://localhost:3001/api/persons


//DELETE http://localhost:3001/api/persons/1

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Arto H",
    "number": "012301230123"
}